version: '3.3'

services:
  api:
    image: timoa/app-stores-prometheus-exporter:latest@sha256:4272f256d241c0f092555263bcef660cc930e4f3faed1574577f8a5ca0def31a
    environment:
      - NODE_ENV=production
    volumes:
      - type: bind
        source: ./config # You need to copy the config files example to the config folder at the root the project
        target: /opt/app/config
    ports:
      - 9514:9514
    restart: always
