version: '3.3'

services:
  api:
    image: timoa/app-stores-prometheus-exporter:latest@sha256:87087921ec8eb541306aeb35eb928c512eb4b4ffd45b2c7df6c45f39d3bf4904
    environment:
      - NODE_ENV=production
    volumes:
      - type: bind
        source: ./config # You need to copy the config files example to the config folder at the root the project
        target: /opt/app/config
    ports:
      - 9514:9514
    restart: always
