version: '3.3'

services:
  api:
    image: timoa/app-stores-prometheus-exporter:latest@sha256:bf12d28c70a94d96bdc530c96fcfbfeefe7bf7b83f50be815271de3be7236835
    environment:
      - NODE_ENV=production
    volumes:
      - type: bind
        source: ./config # You need to copy the config files example to the config folder at the root the project
        target: /opt/app/config
    ports:
      - 9514:9514
    restart: always
