{
 "title": "Mobile App Stores - Per app",
 "description": "Dashboard that shows iTunes and Google Play score and number of reviews per iOS/Android app",
 "tags": [
  "Google Play",
  "iTunes",
  "App Store",
  "Prometheus",
  "Android",
  "iOS"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "store",
    "label": "Store",
    "query": "label_values(appstores_reviews_total, store)"
   },
   {
    "name": "app",
    "label": "App",
    "query": "label_values(appstores_reviews_total, app)"
   },
   {
    "name": "version",
    "label": "Version",
    "query": "label_values(appstores_reviews_total, version)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1><center>App Stores - $app</center></h1>\n\n\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "iTunes - Score",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sort_desc(appstores_score_total{app=~\"$app\",store=\"itunes\",version=\"$version\"})",
     "legendFormat": "$version"
    }
   ]
  },
  {
   "title": "Total Score",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "appstores_score_total{app=~\"$app\",store=\"itunes\", version=\"$version\"}",
     "legendFormat": "iTunes - $version"
    },
    {
     "expr": "appstores_score_total{app=~\"$app\",store=\"gplay\", version=\"$version\"}",
     "legendFormat": "Google Play - $version"
    }
   ]
  },
  {
   "title": "iTunes - Current Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sort_desc(appstores_reviews_total{app=~\"$app\",store=\"itunes\"})"
    }
   ]
  },
  {
   "title": "Google Play - Current Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sort_desc(appstores_reviews_total{app=~\"$app\",store=\"gplay\"})"
    }
   ]
  },
  {
   "title": "Google Play- Score",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sort_desc(appstores_score_total{app=~\"$app\",store=\"gplay\",version=\"$version\"})",
     "legendFormat": "$version"
    }
   ]
  },
  {
   "title": "⭐️⭐️⭐️⭐️⭐️",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(appstores_ratings_5_total{app=~\"$app\",version=\"$version\"})",
     "legendFormat": "$version"
    }
   ]
  },
  {
   "title": "⭐️⭐️⭐️⭐️",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(appstores_ratings_4_total{app=~\"$app\"})",
     "legendFormat": "$version"
    }
   ]
  },
  {
   "title": "⭐️⭐️⭐️",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(appstores_ratings_3_total{app=~\"$app\"})",
     "legendFormat": "$version"
    }
   ]
  },
  {
   "title": "⭐️⭐️",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(appstores_ratings_2_total{app=~\"$app\"})",
     "legendFormat": "$version"
    }
   ]
  },
  {
   "title": "⭐️",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(appstores_ratings_1_total{app=~\"$app\"})",
     "legendFormat": "$version"
    }
   ]
  },
  {
   "title": "Current Version Score (iTunes only)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "appstores_current_version_score_total{app=\"$app\",store=\"itunes\"}",
     "legendFormat": "iTunes"
    }
   ]
  },
  {
   "title": "Score per number of stars (Google Play only)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "appstores_ratings_5_total{app=~\"$app\",version=\"$version\"}",
     "legendFormat": "5 Stars"
    },
    {
     "expr": "appstores_ratings_4_total{app=~\"$app\",version=\"$version\"}",
     "legendFormat": "4 Stars"
    },
    {
     "expr": "appstores_ratings_3_total{app=~\"$app\",version=\"$version\"}",
     "legendFormat": "3 Stars"
    },
    {
     "expr": "appstores_ratings_2_total{app=~\"$app\",version=\"$version\"}",
     "legendFormat": "2 Stars"
    },
    {
     "expr": "appstores_ratings_1_total{app=~\"$app\",version=\"$version\"}",
     "legendFormat": "1 Star"
    }
   ]
  },
  {
   "title": "iTunes - Reviews",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(appstores_reviews_total{app=~\"$app\",store=\"itunes\"})"
    }
   ]
  },
  {
   "title": "Total Reviews",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort_desc(appstores_reviews_total{app=~\"$app\",store=\"itunes\",version=\"$version\"})",
     "legendFormat": "iTunes - $version"
    },
    {
     "expr": "sort_desc(appstores_reviews_total{app=~\"$app\",store=\"gplay\",version=\"$version\"})",
     "legendFormat": "Google Play - $version"
    }
   ]
  },
  {
   "title": "Google Play - Reviews",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sort_desc(appstores_reviews_total{app=~\"$app\",store=\"gplay\"})"
    }
   ]
  },
  {
   "title": "Current Version Reviews (iTunes only)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort_desc(appstores_current_version_reviews_total{app=~\"$app\",store=\"itunes\",version=\"$version\"})",
     "legendFormat": "iTunes - $version"
    }
   ]
  }
 ]
}